pipeline:
  identifier: Build_Boitai_ADT_TEST_1712036528923
  name: Build ADT_TEST
  orgIdentifier: default
  projectIdentifier: GITHUB_EXECUTE
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: Boitai/ADT_TEST
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: account.Github
                    repoName: ADT_TEST
                    cloneDirectory: https://github.com/Boitai/ADT_TEST/blob/main/WELCOME_SCRIPT
                    build:
                      type: branch
                      spec:
                        branch: main
                  description: wecome message execution
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
